spring.application.name=eCommerceBackend
server.port=8085
management.endpoints.jmx.exposure.include=*

####### DB Properties #######
spring.datasource.username=sa
spring.datasource.password=Kamlesh@123
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=eCommerce;encrypt=true;trustServerCertificate=true
spring.jpa.hibernate.ddl-auto=update

####### Spring Security #######
encryption.salt.round=10
jwt.algorithm.key=superSecureSecretKey
jwt.issuer=eCommerce
jwt.expiryInSeconds=604800

####### Email configuration #######
email.from=no-reply@ecommerce.com

####### General configuration #######
app.frontend.url=http://ecommerce.com

####### SMTP configuration #######
spring.mail.host=localhost
spring.mail.port=25
#spring.mail.username=
#spring.mail.password=
#spring.properties.mail.smtp.auth=true
#spring.properties.mail.smtp.starttls.enable=true